[package]
name = "gb_emulator"
version = "0.1.0"
edition = "2021"
description = "A minimalist Gameboy emulator in Rust with always-on GUI and audio."

[dependencies]
blip_buf = ">=0.1.3"
cpal = "0.15"
glium = "0.34"
winit = "0.29"

[profile.release]
lto = true
